# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: a job to say hello
    steps:
    - name: hello world action step
      id: hello
      uses: schapmanCE/container-actions-demo
      with:
        who-to-greet: "billy bob"
    - name: get the output
      run: echo "the time was ${{ step.hello.outputs.time }}"
